import {classifyTask} from '@/lib/task-agent/intent';
import {after} from 'next/server';
import {z} from 'zod';
import {requireUser} from '@/server/auth';
import {ownedRun,runView,controlRun,processRun,hydrateRun,prepareExistingTask} from '@/server/task-agent/service';
import {jsonError} from '@/lib/http';
const input=z.object({action:z.enum(['prepare','answer','cancel','pause','resume','retry','saveDraft']),version:z.number().int().nonnegative(),key:z.enum(['location','urgency','preferences']).optional(),answer:z.string().max(2000).optional(),budget:z.string().max(100).optional(),constraints:z.string().max(500).optional(),candidateId:z.string().max(100).optional()}).superRefine((v,ctx)=>{if(v.key==='location'&&(v.answer?.length??0)>120)ctx.addIssue({code:'custom',message:'Use a city or ZIP, up to 120 characters.'});});
type Context={params:Promise<{id:string}>};
export async function GET(_request:Request,ctx:Context){try{const user=await requireUser();const task=await ownedRun(user.id,(await ctx.params).id);return Response.json({intent:{...classifyTask(task.title,task.notes),eligible:!['COMPLETED','CANCELLED'].includes(task.status)&&classifyTask(task.title,task.notes).eligible},run:task.agentRun?await hydrateRun(runView(task.agentRun)):null},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return jsonError(e);}}
export async function POST(request:Request,ctx:Context){try{const user=await requireUser();const body=input.parse(await request.json());const taskId=(await ctx.params).id;const run=body.action==='prepare'?await prepareExistingTask(user.id,taskId):await controlRun(user.id,taskId,body);if(run.status==='QUEUED')after(()=>processRun(run.id));return Response.json({run:await hydrateRun(run)},{headers:{'Cache-Control':'private, no-store'}});}catch(e){if(e instanceof z.ZodError||(e instanceof Error&&e.message==='INVALID_INPUT'))return Response.json({error:'Please enter a valid answer.'},{status:400});if(e instanceof Error&&['STALE_AGENT_RUN','INVALID_AGENT_TRANSITION','AGENT_RETRY_LIMIT'].includes(e.message))return Response.json({error:e.message==='STALE_AGENT_RUN'?'This run changed. Refresh and try again.':'This action is not available for the current run.'},{status:409});return jsonError(e);}}
