'use client';

import { useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CalendarDays, ChartNoAxesCombined, Check, Clock3, ListChecks, MessageCircle, Mic, Phone, RefreshCcw, ShieldCheck, Sparkles } from 'lucide-react';

const features = [
  { icon: Clock3, title: 'Know what to do next', label: 'Your next move', description: 'Find one useful task that fits your available time, with alternatives and a focus session. Recommendations refresh after task changes and when you return to the app.', prompt: 'I have 38 minutes. What should I do?', answer: 'Make room for your most important work.', rows: [['Finish presentation', '~30 min · Due 5 PM'], ['Call insurance', '~10 min · Alternative'], ['Reply to Damien', '~5 min · Alternative']], note: 'Time, deadlines, dependencies, and work in progress inform the recommendation.' },
  { icon: ListChecks, title: 'Start with your Top 3', label: 'Daily clarity', description: 'Bring priorities, deadlines, and calendar commitments into one briefing. See three recommended focus tasks, ranked by urgency, importance, and capacity.', prompt: 'Give me my full day briefing.', answer: 'A full day. Three clear priorities.', rows: [['1 · Finish presentation', 'Due today · High priority'], ['2 · Review launch notes', 'Unblocks the team'], ['3 · Send the follow-up', 'A short task for later']], note: 'Briefings use your saved tasks, calendar, and working preferences.' },
  { icon: Mic, title: 'Speak. Refine. Keep going.', label: 'Continuous voice', description: 'Capture tasks in a natural voice conversation. Add another task, correct a time, and hear a reply without starting over.', prompt: 'Call Damien tomorrow at 11. Actually, noon.', answer: 'One conversation, with room for corrections.', rows: [['Call Damien', 'Tomorrow · 12:00 PM'], ['Add more context', '“About the roof repair”'], ['Keep talking', 'Add another task or finish']], note: 'Realtime voice requires microphone access. Ambiguous details may need clarification.' },
  { icon: MessageCircle, title: 'Ask about your real day', label: 'Ask Nexdo', description: 'Ask by voice or free-form text about your tasks, calendar, and recommendations. Get contextual help planning or creating work.', prompt: 'Can I find time for a walk tomorrow?', answer: 'Your plans provide the context.', rows: [['Check commitments', 'Review tomorrow’s calendar'], ['Find an opening', 'Use your working preferences'], ['Choose your next step', 'Review the suggested plan']], note: 'Answers use the data available to Nexdo, including the freshness of synced calendars.' },
  { icon: CalendarDays, title: 'Say it. Put it on the calendar.', label: 'Voice appointments', description: 'Create appointments and events through the Calendar voice flow. Refine dates and times conversationally, with calendar entries kept separate from tasks.', prompt: 'Add a dentist appointment Tuesday at 10.', answer: 'A calendar commitment, clearly captured.', rows: [['Dentist appointment', 'Tuesday · 10:00 AM'], ['Confirm the duration', 'Clarify missing details'], ['Calendar event', 'Separate from your task list']], note: 'Creates calendar entries; it does not book with a provider or send invitations.' },
  { icon: ShieldCheck, title: 'See where time gets tight', label: 'Schedule intelligence', description: 'Spot conflicts and capacity problems using task durations, calendar events, working hours, and appointment buffers.', prompt: 'Does everything fit in my day?', answer: 'See the squeeze before you plan around it.', rows: [['Client call', '2:00–2:30 PM'], ['Appointment buffer', 'Leave room between commitments'], ['Presentation work', 'Review the available time']], note: 'Buffers are planning allowances, not live travel estimates.' },
  { icon: RefreshCcw, title: 'Change the plan with confidence', label: 'Fix My Day', description: 'Ask Nexdo to propose a revised schedule when priorities or commitments change. Review moves before applying them, keeping fixed commitments in place.', prompt: 'A meeting came up. Make room for my work.', answer: 'A new plan. Your final say.', rows: [['Client meeting', 'Keep · 2:00 PM'], ['Presentation work', 'Propose · Move to 3:00 PM'], ['Review the changes', 'Approve before applying']], note: 'Replanning proposes changes; it does not continuously detect meetings running late.' },
  { icon: Phone, title: 'Turn a reminder into an action', label: 'Contact actions', description: 'For contact tasks, move from the reminder to Call, Message, Email, or Remind Later. Resolve the right contact and review the action.', prompt: 'Remind me to call Damien about the roof.', answer: 'The next step is within reach.', rows: [['Call Damien', 'Choose the right contact'], ['Call · Message · Email', 'Open the appropriate action'], ['Remind later', 'Come back in 15 minutes']], note: 'Opening a call or composer does not confirm that the conversation happened.' },
  { icon: ChartNoAxesCombined, title: 'See the progress you made', label: 'Weekly review', description: 'Review completed work, focus time, and unfinished priorities in a Monday-to-Sunday summary. Use the perspective to plan what comes next.', prompt: 'How did my week go?', answer: 'More perspective. A clearer next week.', rows: [['Completed work', 'Review what moved forward'], ['Focus time', 'See time spent concentrating'], ['Still on your list', 'Choose what deserves attention']], note: 'Summaries reflect the task and focus activity recorded in Nexdo.' },
  { icon: Sparkles, title: 'Plan around your own rhythm', label: 'Personalized estimates', description: 'Opt in to estimates and completion insights informed by your work history. Notice work patterns and repeated postponements as you plan.', prompt: 'How long should I leave for this work?', answer: 'A plan informed by your experience.', rows: [['Past task durations', 'Learn from recorded work'], ['Personalized estimates', 'Make room for realistic effort'], ['Your choice', 'Opt in or erase learned data']], note: 'Personalization is optional. Predictions are estimates, not guarantees.' },
];

export function AiFeatureShowcase({ detailed = false }: { detailed?: boolean }) {
  const explorer = useRef<HTMLDivElement>(null);
  const [selected, setSelected] = useState(0);
  const [minutes, setMinutes] = useState(38);
  const feature = features[selected];
  const Icon = feature.icon;
  const firstRows = minutes === 10 ? [['Call insurance', '~10 min · Best fit'], ['Reply to Damien', '~5 min · Alternative']] : feature.rows;
  return <section id={detailed ? 'product-features' : 'why-harbour'} className="nf-showcase hs-wrap" aria-labelledby="nf-title">
    <header className="nf-heading"><p className="hs-eyebrow">10 WAYS NEXDO LIGHTENS YOUR DAY</p><h2 id="nf-title">Less organizing.<br /><em>More moving forward.</em></h2><p>From a spoken thought to a clear next step. Explore the intelligence behind your everyday plan.</p></header>
    <div className="nf-explorer" ref={explorer}>
      <div className="nf-copy"><span className="nf-label">{String(selected + 1).padStart(2, '0')} / 10 · {feature.label}</span><h3>{feature.title}</h3><p>{feature.description}</p><p className="nf-detail">{feature.note}</p><Link href={detailed ? '/signup' : '/features/ai-assistant#product-features'} className="hs-text-link">{detailed ? 'Make room for your day' : 'Explore the Product Features'} <ArrowRight size={18} /></Link></div>
      <div className="nf-preview" key={selected} aria-live="polite" aria-atomic="true"><header><span><Sparkles size={17} /> NEXDO IN ACTION</span><small>Illustrative example</small></header><div className="nf-question">“{selected === 0 ? `I have ${minutes} minutes. What should I do?` : feature.prompt}”</div><div className="nf-visual" aria-hidden="true"><div className="nf-orbit" /><Icon size={38} />{selected === 2 && <div className="nf-wave">{[12,24,38,20,32,16,28].map((h,i) => <i key={i} style={{height:h, animationDelay:`${i * 80}ms`}} />)}</div>}</div><h4>{feature.answer}</h4><div className="nf-rows">{(selected === 0 ? firstRows : feature.rows).map(([title, detail], i) => <div key={title} style={{animationDelay:`${i * 70}ms`}}><span className="nf-dot">{i === 0 ? <Check size={14} /> : i + 1}</span><span><strong>{title}</strong><small>{detail}</small></span></div>)}</div>{selected === 0 && <div className="nf-time-choice" role="group" aria-label="Try a sample free-time window"><span>Try an opening</span>{[10,38].map(time => <button key={time} aria-pressed={minutes === time} onClick={() => setMinutes(time)}>{time} min</button>)}</div>}</div>
    </div>
    <div className="nf-grid" role="group" aria-label="Explore ten Nexdo features">{features.map((item,i) => <button key={item.title} aria-pressed={selected === i} onClick={() => {setSelected(i);setMinutes(38); if (explorer.current && explorer.current.getBoundingClientRect().top < 0) explorer.current.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' });}}><item.icon size={23} aria-hidden="true" /><span><small>{String(i + 1).padStart(2,'0')} · {item.label}</small><strong>{item.title}</strong>{detailed && <span className="nf-card-description">{item.description}</span>}</span><ArrowRight className="nf-arrow" size={16} aria-hidden="true" /></button>)}</div>
    <p className="nf-footnote">Explore sample scenarios above. No tasks are created here. Availability varies by plan and platform; continuous voice and contact actions are featured in the native iOS experience. <Link href="/pricing">Compare plans →</Link></p>
  </section>;
}
