'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import type {RunView} from '@/lib/task-agent/types';
const labels:Record<string,string>={NEEDS_INPUT:'One detail before I start',QUEUED:'Research queued',RUNNING:'NexDo is working on this',PAUSED:'Research paused',BLOCKED:'Search connections needed',FAILED:'Research needs a retry',READY_FOR_REVIEW:'Shortlist and drafts ready',NO_RESULTS:'No matching providers found',CANCELLED:'Research cancelled'};
export function TaskAgentCard({taskId}:{taskId:string}){
 const [intent,setIntent]=useState<{category:string;reason:string;eligible?:boolean}|null>(null);
 const [run,setRun]=useState<RunView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [answer,setAnswer]=useState(''),[budget,setBudget]=useState(''),[constraints,setConstraints]=useState('');
 const [drafts,setDrafts]=useState<Record<string,string>>({});
 useEffect(()=>{let stopped=false;const load=async()=>{try{const r=await fetch(`/api/tasks/${taskId}/agent`,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();if(!stopped){setRun(data.run);setIntent(data.intent??null);setError('');}}catch{if(!stopped)setError('Could not refresh task research.');}};void load();const timer=['QUEUED','RUNNING'].includes(run?.status??'')?setInterval(load,4000):undefined;return()=>{stopped=true;clearInterval(timer);};},[taskId,run?.status]);
 async function action(action:string,extra:Record<string,string>={}){if(!run&&action!=='prepare')return;setBusy(true);try{const r=await fetch(`/api/tasks/${taskId}/agent`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,version:run?.version??0,...extra})});const data=await r.json();if(!r.ok)throw Error(data.error??'Could not update research.');setRun(data.run);setAnswer('');setError('');}catch(e){setError(e instanceof Error?e.message:'Could not update research.');}finally{setBusy(false);}}
 if(!run&&intent?.eligible)return <section className="my-4 rounded-xl border p-4"><h3>Find local businesses with Google Places</h3><p>Confirm your city to get a shortlist with phone numbers, addresses, ratings and quote-request drafts.</p><button type="button" disabled={busy} onClick={()=>action('prepare')}>Find businesses</button>{error&&<p role="status">{error}</p>}</section>;
 if(!run)return error?<p role="status">{error}</p>:intent&&['PROCUREMENT','RESEARCH','LOGISTICS'].includes(intent.category)?<p role="status" className="my-4 text-sm">{intent.reason}</p>:null;
 return <section className="rounded-2xl border border-violet-200 bg-violet-50/60 p-4 my-4" aria-label="NexDo task research">
 <h3 className="font-semibold text-violet-800">✦ {labels[run.status]??run.status}</h3>
 <p className="text-sm my-2">{run.service} · {run.slots.location||'Location needed'} · {run.urgency==='urgent'?'Urgent — prioritize availability':'Compare quality and fit'}</p>
 <p className="text-sm">Search uses your city and service with Google Places (and Yelp when connected). NexDo never calls, messages, or shares your contact details with businesses. You review and send drafts yourself. <a href="/places-policy" target="_blank" rel="noopener noreferrer">Search terms and privacy</a></p>
 {run.question&&<div className="my-3 space-y-2"><label className="block font-medium" htmlFor={`agent-answer-${taskId}`}>{run.question.text}</label>
 {run.question.key==='discovery'?<div className="flex gap-3"><button type="button" disabled={busy} onClick={()=>action('answer',{key:'discovery',answer:'yes'})}>Find a professional</button><button type="button" disabled={busy} onClick={()=>action('cancel')}>Keep as a task</button></div>:run.question.key==='urgency'?<div className="flex gap-3"><button type="button" disabled={busy} onClick={()=>action('answer',{key:'urgency',answer:'urgent'})}>Urgent</button><button type="button" disabled={busy} onClick={()=>action('answer',{key:'urgency',answer:'flexible'})}>Can wait</button></div>:run.question.key==='preferences'?<><input aria-label="Budget range (optional)" placeholder="Budget range (optional)" value={budget} maxLength={100} onChange={e=>setBudget(e.target.value)} className="w-full rounded border p-2"/><input aria-label="Requirements (optional)" placeholder="Licensed only, pet-safe, weekends…" value={constraints} maxLength={500} onChange={e=>setConstraints(e.target.value)} className="w-full rounded border p-2"/><button type="button" disabled={busy} onClick={()=>action('answer',{key:'preferences',budget,constraints})}>{budget||constraints?'Start research':'No preference — start research'}</button></>:<><input id={`agent-answer-${taskId}`} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="City or ZIP code" maxLength={120} className="w-full rounded border p-2"/><button type="button" disabled={busy||!answer.trim()} onClick={()=>action('answer',{key:'location',answer})}>Confirm location</button>{run.slots.location&&<button type="button" disabled={busy} onClick={()=>action('answer',{key:'location',answer:run.slots.location})}>Use {run.slots.location}</button>}</>}
 </div>}
 <details className="my-3" open={run.status==='RUNNING'}><summary>View plan and search details</summary><ol>{run.steps.map(step=><li className="my-2" key={step.id}><strong>{step.status==='done'?'✓ ':step.status==='running'?'◉ ':''}{step.title}</strong><p className="text-sm">{step.status} · {step.detail}</p></li>)}</ol></details>
 {run.error&&<p role="status">{run.error}</p>}{run.warnings.map(w=><p key={w} className="text-sm my-2">{w}</p>)}
 {run.candidates.map((c,i)=><details key={c.id} className="rounded-xl border bg-white p-3 my-3"><summary className="font-semibold">{i+1}. {c.name}</summary><p>{c.address}</p>{c.googlePlaceId&&<span translate="no" className="text-sm font-normal text-[#5e5e5e] whitespace-nowrap">Google Maps</span>}<p>{c.phone||'Phone number unavailable'}</p>{c.website&&<a href={c.website} target="_blank" rel="noopener noreferrer">Business website</a>}<p className="my-2 text-sm">{c.reason}</p><div className="flex gap-3">{c.evidence.map(e=><a key={e.source+e.url} href={e.url} target="_blank" rel="noopener noreferrer">View on {e.source}</a>)}</div>{c.attributions?.map((a,i)=><p key={i} className="text-sm">{a.url?<a href={a.url} target="_blank" rel="noopener noreferrer">{a.provider}</a>:a.provider}</p>)}{c.googlePlaceId&&<div className="my-3 border rounded p-2"><h4>Customer feedback · Google Maps</h4><p className="text-sm">A limited selection ordered by Google relevance, not all reviews.</p>{!c.feedback?.length&&<p>No written reviews available.</p>}{c.feedback?.map((r,i)=><blockquote key={i} className="my-3"><div>{r.photoUrl&&<Image unoptimized src={r.photoUrl} alt="" width={32} height={32} className="inline rounded-full"/>}{r.authorUrl?<a href={r.authorUrl} target="_blank" rel="noopener noreferrer">{r.author}</a>:r.author} · {r.rating??'—'}/5 · {r.published}</div><p>{r.text}</p><a href={r.url} target="_blank" rel="noopener noreferrer">Read review on Google Maps</a></blockquote>)}</div>}<label className="block my-2">Your outreach draft<textarea aria-label={`Draft for ${c.name}`} className="block w-full border rounded p-2" rows={7} value={drafts[c.id]??c.draft} onChange={e=>setDrafts({...drafts,[c.id]:e.target.value})} maxLength={2000}/></label><div className="flex gap-3"><button type="button" disabled={busy} onClick={()=>action('saveDraft',{candidateId:c.id,answer:drafts[c.id]??c.draft})}>Save draft</button><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(drafts[c.id]??c.draft);setError('Draft copied. Paste it into your messaging app to send.');}catch{setError('Select and copy the draft text.');}}}>Copy draft</button></div></details>)}
 <div className="flex gap-4 my-3">{['QUEUED','RUNNING'].includes(run.status)&&<button type="button" disabled={busy} onClick={()=>action('pause')}>Pause</button>}{['PAUSED','FAILED','BLOCKED'].includes(run.status)&&<button type="button" disabled={busy} onClick={()=>action(run.status==='PAUSED'?'resume':'retry')}>{run.status==='PAUSED'?'Resume':'Retry'}</button>}{!['CANCELLED','READY_FOR_REVIEW','NO_RESULTS'].includes(run.status)&&<button type="button" disabled={busy} onClick={()=>action('cancel')}>Cancel research</button>}</div>
 {error&&<p role="status">{error}</p>}
 </section>;
}
