'use client';
import { useEffect, useState } from 'react';
import { PageHeading, Panel } from '@/components/admin/admin-ui';
import type { getHealth } from '@/server/health/service';
import type { Status } from '@/server/health/metrics';
type Data=Awaited<ReturnType<typeof getHealth>>&{canOperate:boolean};
const format=(v:number|null|undefined,suffix='')=>v==null?'No telemetry':`${v.toLocaleString(undefined,{maximumFractionDigits:2})}${suffix}`;
const when=(v:string|Date|null|undefined)=>v?new Date(v).toLocaleString():'No telemetry';
function StatusBadge({status}:{status:Status}) {return <span className={`health-status health-${status.toLowerCase()}`}>{status==='Healthy'?'✓':status==='Unknown'?'?':'!'} {status}</span>;}
function Unknown({names}:{names:string[]}) {return <dl className="health-metrics">{names.map(name=><div key={name}><dt>{name}</dt><dd>No telemetry</dd></div>)}</dl>;}
function Coverage({data,name}:{data:Data;name:keyof Data['monitoring']}) {
 const c=data.monitoring[name];
 const note=!data.enabled?'Collection disabled':!data.available?'Storage unavailable':c.reason==='no-activity'?'No requests recorded in this period':c.reason==='inactive'?'No requests in the last 15 minutes':c.reason==='low-traffic'?`Low traffic: ${c.recentRequests} of ${c.minimumSamples} recent observations`:'Recent measurements available';
 return <div><p>{note}. {data.enabled&&data.available?'Request monitoring enabled.':''}</p><p>{c.requests} requests in {data.range} · {c.recentRequests} in the last 15 minutes{c.lastObserved?` · Last activity: ${when(c.lastObserved)}`:''}</p></div>;
}
function Activity({data,name,rows}:{data:Data;name:keyof Data['monitoring'];rows:Data['metrics']}) {
 return <><Coverage data={data} name={name}/><dl className="health-metrics"><div><dt>Recorded requests · {data.range}</dt><dd>{data.available?rows.requests:'Unavailable'}</dd></div><div><dt>Request success</dt><dd>{format(rows.success,'%')}</dd></div><div><dt>P95 response time</dt><dd>{format(rows.p95,' ms')}</dd></div><div><dt>Server errors</dt><dd>{data.available?rows.errors5xx:'Unavailable'}</dd></div><div><dt>Rejected authentication (401/403)</dt><dd>{data.available?rows.authFailures:'Unavailable'}</dd></div><div><dt>Rate limited (429)</dt><dd>{data.available?rows.rateLimits:'Unavailable'}</dd></div></dl></>;
}
export function HealthDashboard({initialData=null}:{initialData?:Data|null}){
 const [range,setRange]=useState('24H');const [data,setData]=useState<Data|null>(initialData);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [revision,refresh]=useState(0);const [loading,setLoading]=useState(!initialData);
 useEffect(()=>{const controller=new AbortController();
 fetch(`/api/admin/health?range=${range}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error(r.status===401?'Your admin session expired. Sign in again.':'System Health is unavailable. Retry shortly.');return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
 const timer=setTimeout(()=>{setLoading(true);setData(null);refresh(v=>v+1);},60000);return()=>{controller.abort();clearTimeout(timer);};},[range,revision]);
 async function action(body:object){setBusy(true);setError('');try{const response=await fetch('/api/admin/health',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);refresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(false);}}
 return <div className="health-dashboard"><PageHeading title="System Health" description="Production operations · measured data only"><button onClick={()=>{setLoading(true);setData(null);setError('');refresh(v=>v+1);}} disabled={loading}>Refresh</button></PageHeading>
 <div className="health-ranges" aria-label="Health time range">{['1H','6H','24H','7D','30D'].map(r=><button key={r} aria-pressed={range===r} onClick={()=>{if(r!==range){setLoading(true);setData(null);setError('');setRange(r);}}}>{r}</button>)}</div>
 {error&&<p role="alert" className="admin-login-error">{error}</p>}{loading&&<p role="status">Loading System Health…</p>}
 {data&&<>
 <Panel title="Overall Health"><StatusBadge status={data.overall}/>{data.overall==='Unknown'&&<p>Monitoring coverage is incomplete. Unknown means insufficient measurements, not a confirmed outage. See each section below.</p>}<p>As of {when(data.asOf)} · automatically refreshes every minute. Status uses the last 15 minutes, with at least five observations.</p><div className="health-overview">{data.sections.map(s=><div key={s.name}><strong>{s.name}</strong><StatusBadge status={s.status}/>{s.name in data.monitoring?<Coverage data={data} name={s.name as keyof Data['monitoring']}/>:s.status==='Unknown'&&<small>{s.name==='iOS'?'Crash telemetry not connected':s.name==='Integrations'?'Some providers have no recent measurements':'Waiting for five recent measurements'}</small>}</div>)}</div>{!data.enabled&&<p role="status">Telemetry collection is not configured. Enable NEXDO_HEALTH_ENABLED after applying the migration.</p>}{(data.processMetrics.counters['health.dropped_events']||data.processMetrics.counters['health.write_failures'])>0&&<p role="alert">This process has dropped or failed telemetry writes. Measurements may be incomplete.</p>}{!data.available&&<p role="alert">Telemetry storage unavailable. Apply the database migration and check database access.</p>}{data.truncated&&<p role="alert">This window exceeds 20,000 observations. Metrics below cover only the newest 20,000; choose a shorter window. Alert evaluation refuses truncated data.</p>}</Panel>
 <Panel title="Active incidents">{data.incidents===null?<p>Incident storage unavailable.</p>:data.incidents.filter(i=>!i.resolvedAt).length===0?<p>No recorded active incidents. This does not establish health; alert evaluation must be scheduled.</p>:data.incidents.filter(i=>!i.resolvedAt).map(i=><article className="health-incident" key={i.id}><h3>{i.severity} · {i.service} · {i.status}</h3><p>{i.trigger}</p><p>Started {when(i.startedAt)} · Duration {Math.round((new Date(data.asOf).getTime()-new Date(i.startedAt).getTime())/60000)} min · Affected users: unknown · Owner: {i.ownerId??'Unassigned'}</p><details><summary>Timeline</summary>{data.audit?.filter(a=>a.targetId===i.id).map(a=><p key={a.id}>{when(a.createdAt)} · {a.action} · {a.detail}</p>)}</details>{data.canOperate&&<div className="health-ranges">{(['ACKNOWLEDGED','INVESTIGATING','RESOLVED'] as const).map(a=><button disabled={busy} key={a} onClick={()=>void action({type:'incident',id:i.id,action:a})}>{a==='ACKNOWLEDGED'?'Acknowledge':a==='INVESTIGATING'?'Investigate':'Resolve'}</button>)}</div>}</article>)}</Panel>
 <dl className="health-metrics health-kpis"><div><dt>Uptime</dt><dd>No telemetry</dd></div><div><dt>P95 API</dt><dd>{format(data.metrics.p95,' ms')}</dd></div><div><dt>API 5xx rate</dt><dd>{format(data.metrics.requests?data.metrics.errors5xx/data.metrics.requests*100:null,'%')}</dd></div><div><dt>Voice session success</dt><dd>No telemetry</dd></div><div><dt>Crash-free sessions</dt><dd>No telemetry</dd></div><div><dt>Active incidents</dt><dd>{data.incidents?.filter(i=>!i.resolvedAt).length??'Unavailable'}</dd></div></dl>
 <Panel title="Production Health Trend"><p>API P95 response latency. Empty intervals have no observations; they are not zero-latency or healthy intervals.</p><div className="health-trend" role="img" aria-label="API P95 latency by time bucket">{data.buckets.map(b=><div key={b.time} title={`${when(b.time)}: ${format(b.p95,' ms')} · ${b.requests} requests · ${b.errors5xx} server errors`}><span style={{height:b.p95===null?2:Math.max(3,b.p95/Math.max(...data.buckets.map(v=>v.p95??0),1)*160)}} className={b.p95===null?'health-no-data':''}/></div>)}</div><details><summary>Accessible trend data</summary><div className="health-table"><table><thead><tr><th>Time</th><th>Requests</th><th>P95</th><th>5xx</th></tr></thead><tbody>{data.buckets.map(b=><tr key={b.time}><td>{when(b.time)}</td><td>{b.requests}</td><td>{format(b.p95,' ms')}</td><td>{b.requests?b.errors5xx:'No telemetry'}</td></tr>)}</tbody></table></div></details></Panel>
 <details className="health-section" open><summary>Application / API health</summary><h3>Endpoints by failures</h3><MetricsTable rows={data.endpoints}/><h3>Slowest endpoints</h3><MetricsTable rows={[...data.endpoints].filter(r=>r.p95!==null).sort((a,b)=>(b.p95??0)-(a.p95??0)).slice(0,10)}/><p>Endpoint names are route templates; request parameters and identifiers are excluded. Request duration measures handler completion, not streamed response completion. Uptime requires an independent probe.</p></details>
 <details className="health-section"><summary>AI services</summary><Activity data={data} name="AI" rows={data.integrations.find(r=>r.name==='OpenAI')!}/><p>Implemented model inventory: {data.modelInventory.join(', ')}. Configuration alone does not establish availability.</p><MetricsTable rows={data.ai}/><p>Grouped by observed model and feature. Realtime credential creation does not measure the subsequent audio session.</p><dl className="health-metrics"><div><dt>Input tokens</dt><dd>{format(data.usage.input)}</dd></div><div><dt>Output tokens</dt><dd>{format(data.usage.output)}</dd></div><div><dt>Total reported tokens</dt><dd>{format(data.usage.input===null?null:data.usage.input+(data.usage.output??0))}</dd></div><div><dt>Estimated cost (USD)</dt><dd>{format(data.usage.cost)}</dd></div></dl><p>Usage reported for {data.usage.reported}/{data.usage.requests} requests; pricing configured for {data.usage.priced}. Totals cover only these observations, excluding streaming, audio and image usage. Cost uses operator-configured per-model rates and does not account for cached-token discounts.</p><details><summary>Cost trend</summary>{data.costTrend.map(b=><p key={b.time}>{when(b.time)}: {format(b.cost,' USD')}</p>)}</details><Unknown names={['Fallback / failover events']}/></details>
 <details className="health-section"><summary>Real-time voice</summary><Activity data={data} name="Voice" rows={data.voice}/><p>Measures voice setup, transcription, speech and tool requests. Live microphone and speaker quality require device session telemetry.</p><MetricsTable rows={[{name:'Voice API requests (not sessions)',status:data.sections.find(s=>s.name==='Voice')!.status,...data.voice}]}/><p>Client-reported minutes for usage records updated in this window: {format(data.voiceReportedMinutes)}. These are cumulative session receipts, not exact minutes spoken within the window.</p><details><summary>Device monitoring coverage</summary><p>Session outcomes, duration, reconnects, audio failures and speech latency are not yet reported by the device. API success does not establish end-to-end voice quality.</p></details><h3>Voice API latency trend · {range}</h3><div className="health-trend" role="img" aria-label="Voice API P95 latency by time bucket">{data.voiceBuckets.map(b=><div key={b.time} title={`${when(b.time)}: ${format(b.p95,' ms')}`}><span style={{height:b.p95===null?2:Math.max(3,b.p95/Math.max(...data.voiceBuckets.map(v=>v.p95??0),1)*160)}} className={b.p95===null?'health-no-data':''}/></div>)}</div><details><summary>Voice trend data</summary>{data.voiceBuckets.map(b=><p key={b.time}>{when(b.time)} · {b.requests} API requests · P95 {format(b.p95,' ms')} · Success {format(b.success,'%')}</p>)}</details><FailureList failures={data.failures.filter(f=>/realtime|voice|speech|transcribe/.test(f.operation))}/></details>
 <details className="health-section"><summary>Integration health</summary><MetricsTable rows={data.integrations}/><p>Web Push uses a separate library and Contacts runs on the device; neither currently emits request timings. No grocery checkout integration was found.</p></details>
 <details className="health-section"><summary>Background jobs / scheduler</summary><p>Due automatic Moments jobs: {data.due??'Unavailable'} · Oldest queued: {when(data.oldest)}</p><h3>Moments delivery states</h3>{data.jobs?.map(j=><p key={j.status}>{j.status}: {j._count}</p>)??<p>No telemetry</p>}<h3>Task reminder states</h3>{data.reminders?.map(j=><p key={j.status}>{j.status}: {j._count}</p>)??<p>No telemetry</p>}<h3>Measured job executions</h3><MetricsTable rows={data.jobSummary}/><h3>Latest scheduler executions</h3>{data.heartbeats.length?data.heartbeats.map(h=><p key={h.service}>{h.service}: {when(h.time)} · HTTP {h.status} · {format(h.durationMs,' ms')} · Trace {h.traceId}</p>):<p>No telemetry</p>}<Unknown names={['Dead-letter queue','Average per-job execution time','Calendar/Gmail sync queue','Daily Brief / AI queue']}/><h3>Failed / uncertain Moments deliveries</h3>{data.failedJobs?.map(j=><details key={j.id}><summary>{j.id} · {j.status}</summary><p>Type: Moments email · Created {when(j.createdAt)} · Started {when(j.claimedAt)} · Last state change {when(j.updatedAt)} · Retries {Math.max(0,j.attempts-1)}</p><p>Sanitized error: {j.status==='UNCERTAIN'?'Delivery outcome unconfirmed':'Delivery failed'}. Per-job trace: {j.traceId??'No telemetry'}.</p></details>)??<p>Unavailable</p>}</details>
 <details className="health-section"><summary>Database health · PostgreSQL / Prisma</summary><StatusBadge status={data.database.status}/><p>Current SELECT 1 probe: {format(data.database.latency,' ms')}. This is a connectivity check, not query latency across the application.</p>{data.database.stats&&<dl className="health-metrics"><div><dt>Database connections</dt><dd>{data.database.stats.connections}</dd></div><div><dt>Server connection limit</dt><dd>{data.database.stats.maximum}</dd></div><div><dt>Database size</dt><dd>{format(data.database.stats.bytes/1048576,' MB')}</dd></div><div><dt>Rollbacks since stats reset</dt><dd>{data.database.stats.rollbacks}</dd></div><div><dt>Deadlocks since stats reset</dt><dd>{data.database.stats.deadlocks}</dd></div></dl>}<p>Connection limit is server-wide; database connections do not measure Prisma pool saturation. Rollbacks include intentional rollbacks.</p><Unknown names={['Connection pool saturation','Query P95','Slow queries','Storage capacity utilization','Replication status','Backup status','Last successful backup']}/></details>
 <details className="health-section"><summary>iOS app health</summary><p>Firebase Analytics is implemented for engagement. No crash/performance provider is connected. A typed adapter is available for a future selected provider.</p><Unknown names={['Production version','Version adoption','Crash-free users','Crash-free sessions','Crash count','Hangs','Launch performance','Network failures','Common crashes','Affected versions / devices / iOS','Recent-release regressions']}/></details>
 <details className="health-section"><summary>Security health</summary><Activity data={data} name="Security" rows={data.security}/><MetricsTable rows={[{name:'Authentication endpoints',status:data.sections.find(s=>s.name==='Security')!.status,...data.security}]}/><p>401/403 counts indicate rejected requests, not unique users or confirmed attacks. OTP and password-reset endpoint failures appear below. No request bodies or identities are collected.</p><details><summary>Security monitoring coverage</summary><p>Authentication requests, rejections, rate limits and server failures are measured. Account lockouts, token revocations and anomaly baselines are not separately instrumented.</p></details><FailureList failures={data.failures.filter(f=>/\/auth(?:\/|$)/.test(f.operation))}/></details>
 <details className="health-section"><summary>Local process counters</summary><p>Existing in-memory metrics, limited to the serving process since restart. These are not fleet-wide totals.</p>{Object.entries(data.processMetrics.counters).map(([name,value])=><p key={name}>{name}: {value}</p>)}</details><details className="health-section"><summary>Failures and traces</summary><FailureList failures={data.failures}/></details>
 <details className="health-section"><summary>Alert rules</summary><p>Evaluated over the most recent hour by the protected scheduler endpoint. No notifications are sent until a channel adapter is selected. {data.canOperate?'You have operator permission.':'Read-only: operator permission is required to change rules or incidents.'}</p>{data.rules.map(rule=><form key={rule.id} className="health-rule" onSubmit={e=>{e.preventDefault();const values=new FormData(e.currentTarget);void action({type:'rule',id:rule.id,threshold:Number(values.get('threshold')),minimumSamples:Number(values.get('minimumSamples')),enabled:values.get('enabled')==='on'});}}><strong>{rule.severity} · {rule.label}</strong><label>Threshold <input name="threshold" type="number" min="0" max="1000000" step="any" defaultValue={rule.threshold} required disabled={!data.canOperate}/></label><label>Minimum samples <input name="minimumSamples" type="number" min="1" max="100000" defaultValue={rule.minimumSamples} required disabled={!data.canOperate}/></label><label><input name="enabled" type="checkbox" defaultChecked={rule.enabled} disabled={!data.canOperate}/> Enabled</label>{data.canOperate&&<button disabled={busy}>Save rule</button>}</form>)}</details>
 <details className="health-section"><summary>Admin activity log</summary><p>Append-only database log. Covers incident actions, alert configuration, and instrumented admin authentication. Existing user/plan changes are not retroactively reconstructed.</p>{data.audit?.map(a=><p key={a.id}>{when(a.createdAt)} · {a.actorId} · {a.action} · {a.targetId} · {a.detail}</p>)??<p>Audit storage unavailable.</p>}</details>
 </>}
 </div>;
}
function MetricsTable({rows}:{rows:({name:string;status:string}&Data['metrics'])[]}) {return rows.length?<div className="health-table"><table><thead><tr>{['Service / endpoint','Status','Requests','Req/min','P50','P95','P99','Success','Timeouts / rate','429','4xx / rate','5xx / rate','Auth failures','Last success','Last failure'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><details><summary>{r.name}</summary><p>{r.requests} observations · {r.errors} failed requests. See Failures and traces for correlated errors.</p></details></td><td><StatusBadge status={r.status as Status}/></td><td>{r.requests||'No telemetry'}</td><td>{r.requests?format(r.rpm):'—'}</td><td>{format(r.p50,' ms')}</td><td>{format(r.p95,' ms')}</td><td>{format(r.p99,' ms')}</td><td>{format(r.success,'%')}</td><td>{r.requests?`${r.timeouts} / ${format(r.timeouts/r.requests*100,'%')}`:'—'}</td><td>{r.requests?r.rateLimits:'—'}</td><td>{r.requests?`${r.errors4xx} / ${format(r.errors4xx/r.requests*100,'%')}`:'—'}</td><td>{r.requests?`${r.errors5xx} / ${format(r.errors5xx/r.requests*100,'%')}`:'—'}</td><td>{r.requests?r.authFailures:'—'}</td><td>{when(r.lastSuccess)}</td><td>{when(r.lastFailure)}</td></tr>)}</tbody></table></div>:<p>No telemetry in this period.</p>;}
function FailureList({failures}:{failures:Data['failures']}) {return failures.length?failures.map(f=><details key={f.id}><summary>{when(f.time)} · {f.service} · {f.error}</summary><p>{f.operation} · Trace: <code>{f.traceId}</code></p></details>):<p>No recorded failures in the selected period. Missing telemetry does not establish health.</p>;}
